name = "PoseErrors"
uuid = "0e048aec-5af0-406a-9f6c-fdc882ab1032"
authors = ["Tim Redick <t.redick@irt.rwth-aachen.de>"]
version = "0.1.0"

[deps]
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
SciGL = "e33cfb9f-2574-42f7-bc46-3c25fa028886"
